server:
  port: 8818
spring:
  datasource:
    druid:
      url: ${jdbc.url}
      password: ${jdbc.password}
      username: ${jdbc.username}
      driver-class-name: ${jdbc.driver}
  profiles:
    active: dev
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true






